@URL = http://localhost:8080/api

###

POST {{URL}}/register HTTP/1.1
Content-Type: application/json

{
    "username": "amarine@gmail.com",
    "password": "P@ssw0rd1!"
}

###

GET {{URL}}/climber HTTP/1.1

###
GET {{URL}}/climber/email=.com HTTP/1.1

###
GET {{URL}}/climber/id=1 HTTP/1.1

###

POST {{URL}}/climber HTTP/1.1
Content-Type: application/json

{
    "appUserId": 4,
    "email": "tthing@this.com",
    "firstName": "Bob",
    "lastName": "Jenkins",
    "dob": "1992-03-14",
    "climberSex": "MALE",
    "betaCredits": 1000,
    "enabled": true
}

###
PUT {{URL}}/climber/1 HTTP/1.1
Content-Type: application/json

{
  "climberId": 1,
  "appUserId": 1,
  "email": "amarine@gmail.com",
  "firstName": "NEW",
  "lastName": "Marine",
  "dob": "1981-03-14",
  "climberSex": "MALE",
  "betaCredits": 1000,
  "enabled": true
}

###

PUT {{URL}}/climber/1/disable HTTP/1.1

###

PUT {{URL}}/climber/1/enable HTTP/1.1

###

GET {{URL}}/profile HTTP/1.1

###

GET {{URL}}/profile/username=moderator HTTP/1.1

###

GET {{URL}}/profile/id=1 HTTP/1.1

###

GET {{URL}}/profile/climber-id=1 HTTP/1.1

###

POST {{URL}}/profile HTTP/1.1
Content-Type: application/json 

{
  "climberId": 2,
  "username": "newuser",
  "description": "Profile of climber newuser",
  "locationId": 0,
  "location": null,
  "tradGrade": null,
  "sportGrade": null,
  "boulderGrade": null,
  "iceGrade": null,
  "mixedGrade": null,
  "aidGrade": null,
  "hasTradGear": false,
  "hasSportGear": false,
  "hasRope": false,
  "hasTransportation": false,
  "openToMentor": false,
  "openToMentee": false,
  "numPartners": 0,
  "safetyAttitudeName": "IMPORTANT",
  "safetyAttitude": null,
  "climbingMotivationName": "EXERCISE",
  "climbingMotivation": null,
  "climbingStyleName": null,
  "climbingStyle": null,
  "climbingCountryName": "CANADA",
  "climbingCountry": null,
  "climbingStateName": "INDIANA",
  "climbingState": null,
  "climbingPostalCode": "46077",
  "climbingGymId": 0,
  "enabled": true,
  "public": true
}

###

PUT {{URL}}/profile/4 HTTP/1.1
Content-Type: application/json 

{
  "profileId": 4,
  "climberId": 2,
  "username": "EXTRAnewuser",
  "description": "Profile of climber newuser",
  "locationId": 0,
  "location": null,
  "tradGrade": null,
  "sportGrade": null,
  "boulderGrade": null,
  "iceGrade": null,
  "mixedGrade": null,
  "aidGrade": null,
  "hasTradGear": false,
  "hasSportGear": false,
  "hasRope": false,
  "hasTransportation": false,
  "openToMentor": false,
  "openToMentee": false,
  "numPartners": 0,
  "safetyAttitudeName": "IMPORTANT",
  "safetyAttitude": null,
  "climbingMotivationName": "EXERCISE",
  "climbingMotivation": null,
  "climbingStyleName": null,
  "climbingStyle": null,
  "climbingCountryName": "CANADA",
  "climbingCountry": null,
  "climbingStateName": "INDIANA",
  "climbingState": null,
  "climbingPostalCode": "46077",
  "climbingGymId": 0,
  "enabled": true,
  "public": true
}

###

PUT {{URL}}/profile/1/disable HTTP/1.1

###

PUT {{URL}}/profile/1/enable HTTP/1.1

###

GET {{URL}}/profile/id=1 HTTP/1.1

###

GET {{URL}}/badge HTTP/1.1

###

GET {{URL}}/badge/id=5 HTTP/1.1

###
POST {{URL}}/badge HTTP/1.1
Content-Type: application/json

{
  "name": "Proficient Belayer",
  "description": "This climber has been recognized as a decent belayer",
  "cost": 50,
  "iconPath": "something here",
  "supply": 1000,
  "enabled": true
}

###

PUT {{URL}}/badge/5 HTTP/1.1
Content-Type: application/json

{
  "badgeId": 5,
  "name": "Proficient Belayer",
  "description": "This climber has been recognized as a RADICAL belayer",
  "cost": 75,
  "iconPath": "something here",
  "supply": 1000,
  "enabled": true
}

###

PUT {{URL}}/badge/5/disable HTTP/1.1

###

PUT {{URL}}/badge/5/enable HTTP/1.1

###

GET {{URL}}/climber-badge HTTP/1.1

###

GET {{URL}}/climber-badge/id=4 HTTP/1.1

###

GET {{URL}}/climber-badge/awardee=2 HTTP/1.1

###

GET {{URL}}/climber-badge/giver=3 HTTP/1.1

###

GET {{URL}}/climber-badge/badge=2 HTTP/1.1

###

POST {{URL}}/climber-badge HTTP/1.1
Content-Type: application/json

{
    "awardeeId": 2,
    "badgeId": 2,
    "giverId": 1,
    "dateAwarded": "2023-01-01",
    "enabled": true
}

###

PUT {{URL}}/climber-badge/4 HTTP/1.1
Content-Type: application/json

{
    "climberBadgeId": 4,
    "awardeeId": 1,
    "badgeId": 3,
    "giverId": 1,
    "dateAwarded": "2023-01-01",
    "enabled": true
}

###

PUT {{URL}}/climber-badge/4/disable HTTP/1.1

###

PUT {{URL}}/climber-badge/4/enable HTTP/1.1

###

GET {{URL}}/climbing-gym HTTP/1.1

###

GET {{URL}}/climbing-gym/id=5 HTTP/1.1

###

POST {{URL}}/climbing-gym HTTP/1.1
Content-Type: application/json

{
  "name": "Climbing Gym 5",
  "locationId": 1,
  "location": null,
  "enabled": true
}

###

PUT {{URL}}/climbing-gym/5 HTTP/1.1
Content-Type: application/json

{
    "gymId": 5,
    "name": "New Climbing Gym!!!",
    "locationId": 2,
    "location": null,
    "enabled": true
}

###

PUT {{URL}}/climbing-gym/4/disable HTTP/1.1

###

PUT {{URL}}/climbing-gym/4/enable HTTP/1.1

###

GET {{URL}}/profile-comment HTTP/1.1

###

GET {{URL}}/profile-comment/id=4 HTTP/1.1

###

GET {{URL}}/profile-comment/receiver=2 HTTP/1.1

###

GET {{URL}}/profile-comment/poster=0 HTTP/1.1

###

POST {{URL}}/profile-comment HTTP/1.1
Content-Type: application/json

{
    "postingClimberId": 1,
    "receivingClimberId": 2,
    "subject": "new comment!!!",
    "text": "User 2 is a tremendous n00b!",
    "postedTimeString": "2020-01-01 18:24:22",
    "postedTime": null,
    "enabled": true
  }

###

PUT {{URL}}/profile-comment/4 HTTP/1.1
Content-Type: application/json

{   
    "profileCommentId": 4,
    "postingClimberId": 3,
    "receivingClimberId": 2,
    "subject": "CHANGED",
    "text": "User 2 is a tremendous n00b!",
    "postedTimeString": "2020-01-01 18:24:22",
    "postedTime": null,
    "enabled": true
  }

###

PUT {{URL}}/profile-comment/4/disable HTTP/1.1

###

PUT {{URL}}/profile-comment/4/enable HTTP/1.1

###

GET {{URL}}/location HTTP/1.1

###

GET {{URL}}/location/5 HTTP/1.1

###

POST {{URL}}/location HTTP/1.1
Content-Type: application/json

{
  "country": "MEXICO",
  "stateProvince": "ALABAMA",
  "city": "Mobile",
  "postalCode": "99999",
  "locationCode": 1,
  "enabled": true
}

###

PUT {{URL}}/location/5 HTTP/1.1
Content-Type: application/json

{
  "locationId": 5,
  "country": "CANADA",
  "stateProvince": "ALABAMA",
  "city": "Mobile",
  "postalCode": "99999",
  "locationCode": 1,
  "enabled": true
}

###

PUT {{URL}}/location/5/disable HTTP/1.1

###

PUT {{URL}}/location/5/enable HTTP/1.1
